server:
  port: 1299

zuul:
  ignored-services: '*'
  prefix: /services
  routes:
    system:     # 路由名称
      path: /system/**       # 路由匹配的路径
      serviceId: system-service       # 路径匹配的服务名称
    course:     # 路由名称
      path: /course/**       # 路由匹配的路径
      serviceId: course-service       # 路径匹配的服务名
    file:     # 路由名称
      path: /file/**       # 路由匹配的路径
      serviceId: file-service       # 路径匹配的服务名
    cache:     # 路由名称
      path: /cache/**       # 路由匹配的路径
      serviceId: cache-service       # 路径匹配的服务名
    elasticsearch:     # 路由名称
      path: /elasticsearch/**       # 路由匹配的路径
      serviceId: elasticsearch-service       # 路径匹配的服务名
    user:     # 路由名称
      path: /user/**       # 路由匹配的路径
      serviceId: user-service       # 路径匹配的服务名

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #以ip进行注册
    instance-id: zuul-server:1299 #注册的服务的实例的标识

spring:
  application:
    name: ZUUL-SERVER