server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #以ip进行注册
    instance-id: cache-service:8002 #注册的服务的实例的标识

spring:
  application:
    name: CACHE-SERVICE
feign:
   hystrix:
       enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
