server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #以ip进行注册
    instance-id: file-service:8001 #注册的服务的实例的标识

spring:
  application:
    name: FILE-SERVICE